### ISSUE TITLE
Stopped working after updating Stream Deck v6.6.0 (20583)

### ISSUE THREAD

**Issue by tqvalenca** [ArtemNeFRiT/streamdeck-youtube-statistics#1]
Stopped working after updating Stream Deck v6.6.0 (20583). 

Symptons: It doesn't show any stats, and display the yellow sign when clicked.

What I've tried to troubleshoot:
- tested the API key generated to other Youtube Stats Plugin and it didn't worked;
- tested the API key I was using with this plugin on the other Youtube Stats Plugin and it *DID* work (so the key isn't likely the problem);
- Generated a new API key using [this steps](https://github.com/ArtemNurtdinov/streamdeck-youtube-statistics?tab=readme-ov-file#api-key) and it didn't work.

I can't think any other things to do as I'm not familiar with your code nor Youtube's API.

**Comment by ArtemNurtdinov** [comment]
Greetings!

Thank you for the feedback regarding the operation of my "YouTube Stats Tracker" plugin.
I have updated my Stream Deck to version 6.6.0 in hopes of reproducing the error, but surprisingly, I have not encountered any issues with the plugin's functionality.
Please make sure you are using the latest version of the plugin (1.2).
Is the problem still persisting?

**Comment by tqvalenca** [comment]
I am. Well, once you've confirmed it should work I began thinking what could I try next then I realized that I could uninstall then reinstall the plugin. Once done, it finally worked. Sorry for your trouble.

**Comment by mattboston** [comment]
Is there any way to get this to work on MacOS?

**Comment by mattboston** [comment]
> Is there any way to get this to work on MacOS?

NVM, uninstalled then reinstalled and it's working now.
